baseURL = "https://www.tayleyi.com"
languageCode = "en-us"
title = "Taylor Yang"
theme = "typo"
description = "Currently looking for entry-level in software engineering or data science. Graduating in spring 2025."
copyright = "&copy; 2024"

[taxonomies]
tag = 'tags'

[params]
#  author = "Taylor Yang"
  description = "New graduate portfolio page for Taylor Yang. Includes personal projects, school assignments, and more."
  header_subtitle = """
    Currently looking for entry-level in software engineering or data science.
    Graduating in spring 2025.
    """
  homeIntroContent = "Currently looking for entry-level in software engineering or data science. Graduating in spring 2025."
  homeCollectionTitle = "Projects"
  homeCollection = "posts"
  paginationSize = 100
  listSummaries = false
  breadcrumbs = true
  colorPalette = 'catpuccin'

  [[params.menu]]
    name = "posts"
    url = "/posts"
  [[params.menu]]
    name = "tags"
    url = "/tags"
  [[params.menu]]
    name = "about"
    url = "/about"

  [[params.social]]
    name = "cv"
    url = "/TaylorYang_Resume_SoftwareEngineering_Oct2024.pdf"
  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/yang-taylor"
  [[params.social]]
    name = "github"
    url = "https://github.com/yang-taylor"
  [[params.social]]
    name = "email"
    url = "mailto:tayloryang9264@gmail.com"