baseURL = "https://www.tayleyi.com"
languageCode = "en-us"
title = "Taylor Yang"
theme = "typo"
description = "Currently looking for entry-level in software engineering or data science. Graduating in spring 2025."
copyright = "&copy; 2024"

[taxonomies]
tag = 'tags'

[params]
#  author = "Taylor Yang"
  description = "New graduate portfolio page for Taylor Yang. Includes personal projects, school assignments, and more."
  header_subtitle = "Currently looking for entry-level in software engineering or data science. Graduating in spring 2025."
  homeIntroContent = "Currently looking for entry-level in software engineering or data science. Graduating in spring 2025."
  homeCollectionTitle = "Posts"
  homeCollection = "posts"
  paginationSize = 100
  listSummaries = false
  breadcrumbs = true

  color = 'light'
  github = "yang-taylor"
  linkedin = "yang-taylor"

  [[params.social]]
    name = "linkedin"
    href = "https://linkedin.com/in/yang-taylor"
  [[params.social]]
    name = "github"
    href = "https://github.com/yang-taylor"
  [[params.social]]
    name = "email"
    href = "mailto:tayloryang9264@gmail.com"